// Default Expression Library
const legacyLibrary = {
    "Text": [
        { id: 101, name: "Lock Gradient Ramp to Text", code: "// Apply to Gradient Ramp's Start and End positions\nthisLayer.toComp(value);\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#2ed573" },
        { id: 102, name: "Auto Center Anchor Point", code: "// Apply to Text Layer's Anchor Point\nr = sourceRectAtTime(time, false);\n[r.left + r.width/2, r.top + r.height/2];\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#2ed573" },
        { id: 103, name: "Typewriter with Cursor", code: "// Apply to Source Text\nn = Math.min(text.sourceText.length, Math.floor(time * effect(\"Speed\")(\"Slider\")));\ntext.sourceText.substr(0, n) + \"|\";\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Speed", matchName: "ADBE Slider Control" }], color: "#2ed573" },
        { id: 104, name: "Digital Clock", code: "// Apply to Source Text\nh = Math.floor(time / 3600);\nm = Math.floor(time / 60) % 60;\ns = Math.floor(time % 60);\n[h, m, s].map(x => x < 10 ? \"0\" + x : x).join(\":\");\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#2ed573" },
        { id: 105, name: "Number Counter", code: "// Apply to Source Text\nn = Math.round(value);\nn.toLocaleString();\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#2ed573" },
        { id: 106, name: "Glitched Text", code: "// Apply to Source Text\noriginalText = text.sourceText;\nglitchSpeed = effect(\"Speed\")(\"Slider\");\ncorruptionLevel = effect(\"Corruption\")(\"Slider\") / 100;\n\n// Full range of printable Unicode characters approximation\nunicodeStart = 33;  // \"!\"\nunicodeEnd = 126;   // \"~\"\n\nresult = \"\";\nseedRandom(Math.floor(time * glitchSpeed * 10), true);\n\nfor (i = 0; i < originalText.length; i++) {\n    char = originalText.charAt(i);\n    if (char == \" \") {\n        result += \" \";\n        continue;\n    }\n    if (random() < corruptionLevel) {\n        switch (Math.floor(random(4))) {\n            case 0: \n                // Pick random printable ASCII character\n                result += String.fromCharCode(Math.floor(random(unicodeStart, unicodeEnd+1)));\n                break;\n            case 1: \n                // Duplicate the original char for glitchy effect\n                result += char + char;\n                break;\n            case 2: \n                // Randomize case\n                result += (random() > 0.5) ? char.toUpperCase() : char.toLowerCase();\n                break;\n            case 3: \n                // Pick a random high Unicode block for “weird” symbols\n                result += String.fromCharCode(Math.floor(random(0x2500, 0x25FF))); // Box-drawing block\n                break;\n        }\n    } else {\n        result += char;\n    }\n}\nresult;\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Speed", matchName: "ADBE Slider Control" }, { name: "Corruption", matchName: "ADBE Slider Control" }], color: "#2ed573" }
    ],
    "Time": [
        { id: 201, name: "Loop (Dropdown Select)", code: "// Apply to any keyframed property\nloopMap = [\"cycle\", \"pingpong\", \"offset\"];\ntype = loopMap[effect(\"Loop Type\")(\"Menu\") - 1];\nloopOut(type);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Loop Type", matchName: "ADBE Dropdown Control" }], color: "#1e90ff" },
        { id: 203, name: "Posterize Time", code: "// Apply to any property\nposterizeTime(effect(\"Frame Rate\")(\"Slider\"));\nvalue;\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frame Rate", matchName: "ADBE Slider Control" }], color: "#1e90ff" },
        { id: 204, name: "Start / End at Time", code: "// Apply to any property\ntime > inPoint && time < outPoint ? value : valueAtTime(inPoint);\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#1e90ff" },
        { id: 205, name: "Simple Time Driver", code: "// Apply to any property\ntime * 100;\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#1e90ff" },
        { id: 206, name: "Delay Index Value", code: "// Apply to any property (e.g. Rotation)\ndelayFrames = effect(\"Delay Frames\")(\"Slider\");\ndelayTime = delayFrames * thisComp.frameDuration * (index - 1);\nthisComp.layer(1).rotation.valueAtTime(time - delayTime);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Delay Frames", matchName: "ADBE Slider Control" }], color: "#1e90ff" }
    ],
    "Wiggle": [
        { id: 301, name: "Choppy Stop Motion", code: "// Apply to any property\nposterizeTime(effect(\"Frame Rate\")(\"Slider\"));\nwiggle(effect(\"Frequency\")(\"Slider\"), effect(\"Amplitude\")(\"Slider\"));\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frame Rate", matchName: "ADBE Slider Control" }, { name: "Frequency", matchName: "ADBE Slider Control" }, { name: "Amplitude", matchName: "ADBE Slider Control" }], color: "#ffa502" },
        { id: 302, name: "Random Flicker Opacity", code: "// Apply to Opacity property\nposterizeTime(effect(\"Frame Rate\")(\"Slider\"));\nrandom(0, 100);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frame Rate", matchName: "ADBE Slider Control" }], color: "#ffa502" },
        { id: 303, name: "Wiggle 1D (X Only)", code: "// Apply to 2D Position property\nx = wiggle(effect(\"Frequency\")(\"Slider\"), effect(\"Amplitude\")(\"Slider\"))[0];\n[x, value[1]];\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frequency", matchName: "ADBE Slider Control" }, { name: "Amplitude", matchName: "ADBE Slider Control" }], color: "#ffa502" },
        { id: 304, name: "Wiggle Loop", code: "// Apply to any property\nfreq = effect(\"Frequency\")(\"Slider\");\namp = effect(\"Amplitude\")(\"Slider\");\nloopDur = effect(\"Duration\")(\"Slider\");\nw = wiggle(freq, amp, 1, 0.5, time % loopDur);\nw;\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frequency", matchName: "ADBE Slider Control" }, { name: "Amplitude", matchName: "ADBE Slider Control" }, { name: "Duration", matchName: "ADBE Slider Control" }], color: "#ffa502" }
    ],
    "Transform": [
        { id: 401, name: "Exponential Scale", code: "// Apply to Scale property\nfreq = effect(\"Frequency\")(\"Slider\");\namp = effect(\"Amplitude\")(\"Slider\");\nw = wiggle(freq, amp);\nvalue * (1 + w);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frequency", matchName: "ADBE Slider Control" }, { name: "Amplitude", matchName: "ADBE Slider Control" }], color: "#ff4757" },
        { id: 402, name: "Random Layer Scale", code: "// Apply to Scale property\nseedRandom(index, true);\n[random(50, 150), random(50, 150)];\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#ff4757" },
        { id: 403, name: "Maintain Stroke Width", code: "// Apply to Stroke Width property\nvalue / max(length(toComp([0, 0]), toComp([0.7071, 0.7071])), 0.001);\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#ff4757" },
        { id: 404, name: "Procedural Sine Path", code: "// Apply to Shape Path property\namp = effect(\"Amplitude\")(\"Slider\");\nwLen = effect(\"Wavelength\")(\"Slider\");\nlengthTotal = effect(\"Length\")(\"Slider\");\npts = [];\nfor (i = 0; i < 200; i++) {\n  t = i / 199;\n  x = t * lengthTotal - lengthTotal / 2;\n  y = amp * Math.sin(t * lengthTotal / wLen * 2 * Math.PI);\n  pts.push([x, y]);\n}\ncreatePath(pts, [], [], false);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Amplitude", matchName: "ADBE Slider Control" }, { name: "Wavelength", matchName: "ADBE Slider Control" }, { name: "Length", matchName: "ADBE Slider Control" }], color: "#ff4757" },
        { id: 405, name: "Heartbeat Pulse", code: "// Apply to Scale property\nfreq = effect(\"Frequency\")(\"Slider\");\namp = effect(\"Amplitude\")(\"Slider\");\nvalue + Math.sin(time * freq * 2 * Math.PI) * amp;\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Frequency", matchName: "ADBE Slider Control" }, { name: "Amplitude", matchName: "ADBE Slider Control" }], color: "#ff4757" },
        { id: 406, name: "Circular Orbit", code: "// Apply to Position property\nspeed = effect(\"Speed\")(\"Slider\");\nradius = effect(\"Radius\")(\"Slider\");\n\na = time * speed;\nvalue + [Math.cos(a) * radius, Math.sin(a) * radius, 0];\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Speed", matchName: "ADBE Slider Control" }, { name: "Radius", matchName: "ADBE Slider Control" }], color: "#ff4757" }
    ],
    "Utility": [],
    "Color": [
        { id: 601, name: "Rainbow Cycle", code: "// Apply to any color property\nspeed = effect(\"Speed\")(\"Slider\");\nh = (time * speed) % 1;\nhslToRgb([h, 1, 0.5, 1]);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "Speed", matchName: "ADBE Slider Control" }], color: "#ffffff" },
        { id: 602, name: "Random Color Per Second", code: "// Apply to any color property\nseedRandom(Math.floor(time), true);\n[random(), random(), random()];\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#ffffff" },
        { id: 603, name: "Brightness Pulse (Same Hue)", code: "// Apply to any color property\nh = 0.6;\nl = 0.5 + Math.sin(time * 4) * 0.25;\nhslToRgb([h, 1, l]);\n// ®Wrangle by Jose \"Hazrd\" Lopez", color: "#ffffff" }
    ],
    "3D": [
        { id: 702, name: "2D to 3D Space Null", code: "// Apply to 2D Position property\nthisComp.layer(effect(\"3D Layer\")(\"Layer\")).toComp([0, 0, 0]);\n// ®Wrangle by Jose \"Hazrd\" Lopez", controllers: [{ name: "3D Layer", matchName: "ADBE Layer Control" }], color: "#a29bfe" }
    ],
    "Custom": []
};

